name: CI

on:
  push:
    branches: [ main ]
  pull_request: # Allow building on any PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ğŸš Shellcheck scripts ğŸš
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        run: ./shellcheck.sh
